//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMPE2800_Lab02.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CMPE2800_Lab02.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ammoDrop {
            get {
                object obj = ResourceManager.GetObject("ammoDrop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;LEVEL&gt;
        ///	&lt;LEVELTYPE&gt;CITY&lt;/LEVELTYPE&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;4&lt;/X&gt;
        ///		&lt;Y&gt;2&lt;/Y&gt;
        ///		&lt;TYPE&gt;WEAK&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;hl&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;8&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;1&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;3&lt;/X&gt;
        ///		&lt;Y&gt;4&lt;/Y&gt;
        ///		&lt;TYPE&gt;WEAK&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;l&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;1&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;4&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;5&lt;/X&gt;
        ///		&lt;Y&gt;5&lt;/Y&gt;
        ///		&lt;TYPE&gt;HARD&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;2&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;2&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;9&lt;/X&gt;
        ///		&lt;Y&gt;5&lt;/Y&gt;
        ///		&lt;TYPE&gt;HARD&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CityLevel {
            get {
                return ResourceManager.GetString("CityLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CityTerrain {
            get {
                object obj = ResourceManager.GetObject("CityTerrain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;LEVEL&gt;
        ///	&lt;LEVELTYPE&gt;DESERT&lt;/LEVELTYPE&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;7&lt;/X&gt;
        ///		&lt;Y&gt;0&lt;/Y&gt;
        ///		&lt;TYPE&gt;WEAK&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;2&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;3&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;7&lt;/X&gt;
        ///		&lt;Y&gt;9&lt;/Y&gt;
        ///		&lt;TYPE&gt;WEAK&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;2&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;3&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;0&lt;/X&gt;
        ///		&lt;Y&gt;5&lt;/Y&gt;
        ///		&lt;TYPE&gt;WEAK&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;4&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;2&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;12&lt;/X&gt;
        ///		&lt;Y&gt;5&lt;/Y&gt;
        ///		&lt;TYPE&gt;WEAK&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DesertLevel {
            get {
                return ResourceManager.GetString("DesertLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DesertTerrain {
            get {
                object obj = ResourceManager.GetObject("DesertTerrain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DirtTerrain {
            get {
                object obj = ResourceManager.GetObject("DirtTerrain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos;?&gt;
        ///&lt;LEVEL&gt;
        ///	&lt;LEVELTYPE&gt;GRASS&lt;/LEVELTYPE&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;3&lt;/X&gt;
        ///		&lt;Y&gt;2&lt;/Y&gt;
        ///		&lt;TYPE&gt;HARD&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;2&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;2&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;11&lt;/X&gt;
        ///		&lt;Y&gt;2&lt;/Y&gt;
        ///		&lt;TYPE&gt;HARD&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;2&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;2&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;3&lt;/X&gt;
        ///		&lt;Y&gt;8&lt;/Y&gt;
        ///		&lt;TYPE&gt;HARD&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHAPE&gt;
        ///		&lt;WIDTH&gt;2&lt;/WIDTH&gt;
        ///		&lt;HEIGHT&gt;2&lt;/HEIGHT&gt;
        ///	&lt;/WALL&gt;
        ///	&lt;WALL&gt;
        ///		&lt;X&gt;11&lt;/X&gt;
        ///		&lt;Y&gt;8&lt;/Y&gt;
        ///		&lt;TYPE&gt;HARD&lt;/TYPE&gt;
        ///		&lt;SHAPE&gt;o&lt;/SHA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GrassLevel {
            get {
                return ResourceManager.GetString("GrassLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GrassTerrain {
            get {
                object obj = ResourceManager.GetObject("GrassTerrain", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rockets {
            get {
                object obj = ResourceManager.GetObject("rockets", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap shell {
            get {
                object obj = ResourceManager.GetObject("shell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
